export { default as Main } from './Main/Main'
export { default as BlogPage } from './Blog/BlogPage'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as ExperiencePage } from './Experience/ExperiencePage'
export { default as SkillsPage } from './Skills/SkillsPage'
